### ISSUE TITLE
Dependency of FVP models on python39.dll

### ISSUE THREAD

**Issue by rebolloluis** [Arm-Examples/AVH_CI_Template#2]
I'm setting up a Jenkins pipeline based on this template and came across the same issue I reported on Arm-Examples/AVH-VSI#13. I'm opening an new one here to see if someone else has had a similar problem on this repo too.

TL:DR
FVP models won't run locally until I do either of two things:
1. Install Python 3.9 and add it to PATH (not clearly documented as a dependency).
2. Manually add `python39.dll` to `$env:USERPROFILE/.vcpkg/downloads/artifacts/2139c4c6/models.arm.avh.fvp/11.26.11/bin/models/` folder.

It's the same problem whether I use CMSIS VSCode extension, or do everything from the CLI. I'm not using any cloud services. My nodes are local Windows 10 PCs used as Jenkins agents, so I want the job to be reproducible on any of machine. The problem is, we already have a couple of Python versions installed on all these nodes (3.7 and 3.11) so having to add Python 3.9 only to solve this dependency seems unnecessary. E.g. considering that `report.py` works just fine with 3.11 in our case.

Furthermore, I also have Keil MDK v6 installed (with PRO license), and when looking at the folder where the FVP executables are located, I do see this `python39.dll` there, hence no issues running those.

Possible solutions (ordered from most preferred to least):
1. Add the missing python39.dll dependency to the registry of the AVH models (e.g. `arm:models/arm/avh-fvp 11.26.11`). This not only solves the problem but also removes the need to install Python 3.9 specifically.
2. Document _somewhere_ in the README that the user must install Python 3.9 and add it to PATH.
3. ?

Please let me know if I'm missing something as I'm relatively new to this. I'm happy try any solutions the maintainers propose. Thanks, for reading!

**Comment by rebolloluis** [comment]
See answer from https://github.com/Arm-Examples/AVH-VSI/issues/13#issuecomment-2278158139.

**Comment by KeilChris** [comment]
Thanks for pointing to @vovamarch's answer. I'm closing this one here.
